#!/bin/sh
#
# Configuring host communication.
#

IP_OF_HOST="172.29.251.101"

case "$1" in
  start)
    printf "Configuring host communication."
    
    /sbin/ifconfig eth0 192.168.1.10 up
    /sbin/route add -host $IP_OF_HOST dev eth0
    /sbin/route add default gw $IP_OF_HOST
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Shutdown host communication. "
    /sbin/route del default
    /sbin/ifdown -a
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?


